version: '3'

services:

  api:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/roche_shopping_cart
    ports:
      - 8000:8000
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - database
      - reservation-service

  database:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_db_user -d test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    restart: always

  reservation-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/reservation-service/stubs:/home/wiremock
    ports:
      - "8081:8080"

volumes:
  postgres_data:
